FROM golang:1.10.0-alpine as golang
RUN apk add -U --no-cache ca-certificates make
COPY . /go/
WORKDIR /go
RUN go get -v ./...
RUN FLAVOR=nightly CGO_ENABLED=0 make

FROM scratch
WORKDIR /
COPY LICENSE BINARY_LICENSE /
COPY --from=golang /go .
COPY --from=golang /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
ENTRYPOINT ["./autospotting"]
